//! The cron writer.
//!
//! cron has two very different storage models and one writer has to
//! serve both. A per-user crontab is not a file we may touch: it is
//! whatever `crontab -l` prints and whatever `crontab -` accepts, so
//! every mutation is read-modify-reinstall through the binary, which is
//! also what makes the spool file's ownership and the daemon's rescan
//! come out right. `/etc/crontab` and `/etc/cron.d/*` are ordinary root
//! files with an extra user column, edited in place through
//! [`LineFile`] so the operator's comments and alignment survive.
//!
//! Every operation is the same three beats: plan against the host
//! (reads only), hand the plan to [`execute`], then work out the id the
//! read path would mint for what we just wrote. The last beat is not
//! free for per-user crontabs — a line number only means something
//! relative to `crontab -l`'s current output, header included — so
//! create and update re-list and match on schedule plus command.

use std::sync::Arc;
use std::time::Duration;

use shuvjobs_core::host::shell::{shell_quote, shell_safe_username};
use shuvjobs_core::host::{Host, HostOs, Privilege};
use shuvjobs_core::manage::{
    execute, ApplyMode, Change, FailPolicy, JobScope, JobSpec, JobWriter, MutationOutcome,
};
use shuvjobs_core::{Error, Result, ScheduleType, TaskSourceKind};

use crate::cron::CronAdapter;
use crate::ids::{parse_cron_id, CronId};
use crate::lineedit::{strip_disabled_marker, LineFile};
use crate::write::{
    validate_command, validate_simple_name, NameKind, DISABLED_MARKER, MANAGED_MARKER,
};

/// The `@` shorthands cron accepts in place of five fields.
const CRON_ALIASES: &[&str] = &[
    "@reboot",
    "@hourly",
    "@daily",
    "@weekly",
    "@monthly",
    "@yearly",
    "@annually",
];

/// The lines cronie prepends to `crontab -l` output. They are re-added
/// on every install, so feeding them back would grow the file by three
/// lines a time.
fn is_install_header_line(line: &str) -> bool {
    let trimmed = line.trim_end();
    trimmed.starts_with("# DO NOT EDIT THIS FILE")
        || (trimmed.starts_with("# (") && trimmed.contains("installed on"))
        || trimmed.starts_with("# (Cron version")
}

/// Drop cronie's install banner from the front of a crontab.
///
/// At most three lines, and only from the very top: a line that is not
/// part of the banner stops the scan, so a comment the operator wrote
/// is never mistaken for ours.
pub fn strip_install_header(text: &str) -> String {
    let mut rest = text;
    for _ in 0..3 {
        let (line, tail) = match rest.split_once('\n') {
            Some((line, tail)) => (line, tail),
            None => (rest, ""),
        };
        if !is_install_header_line(line) {
            break;
        }
        rest = tail;
    }
    rest.to_string()
}

fn unsupported(id: &str, reason: &str) -> Error {
    Error::Unsupported {
        source_kind: TaskSourceKind::Cron,
        id: id.to_string(),
        reason: reason.to_string(),
    }
}

fn drifted(id: &str) -> Error {
    Error::Conflict(format!(
        "{id}: no job on that line any more; the crontab changed since it was read, refresh and retry"
    ))
}

/// cron treats an unescaped `%` as "end of command, rest is stdin", which
/// is a favourite way to lose a `date +%F`. We still write it — it is
/// occasionally what the operator meant — but never silently.
fn percent_note(command: &str) -> Option<String> {
    let unescaped = command
        .char_indices()
        .any(|(i, c)| c == '%' && !command[..i].ends_with('\\'));
    unescaped.then(|| {
        "the command contains `%`: cron reads an unescaped `%` as a newline and feeds \
         the rest to the job on stdin; escape it as `\\%` if you meant a literal percent"
            .to_string()
    })
}

/// One parsed crontab job line, with the command's own spacing kept.
#[derive(Debug, Clone, PartialEq, Eq)]
struct JobLine {
    expr: String,
    user: Option<String>,
    command: String,
}

/// Byte offset just past the first `count` whitespace-separated fields.
fn skip_fields(line: &str, count: usize) -> Option<usize> {
    let bytes = line.as_bytes();
    let mut i = 0;
    for _ in 0..count {
        while i < bytes.len() && bytes[i].is_ascii_whitespace() {
            i += 1;
        }
        if i >= bytes.len() {
            return None;
        }
        while i < bytes.len() && !bytes[i].is_ascii_whitespace() {
            i += 1;
        }
    }
    Some(i)
}

/// Split a crontab line into schedule, user (system files only), and
/// command. `None` for anything that is not a job: blanks, comments,
/// environment assignments, and truncated lines.
fn parse_job_line(line: &str, has_user_field: bool) -> Option<JobLine> {
    let line = line.trim();
    if line.is_empty() || line.starts_with('#') {
        return None;
    }
    let tokens: Vec<&str> = line.split_whitespace().collect();
    let first = *tokens.first()?;
    // `PATH=/usr/bin` and friends are settings, not jobs.
    if first.contains('=') {
        return None;
    }
    let schedule_fields = if first.starts_with('@') { 1 } else { 5 };
    let leading = schedule_fields + usize::from(has_user_field);
    if tokens.len() <= leading {
        return None;
    }
    let command = line[skip_fields(line, leading)?..].trim();
    if command.is_empty() {
        return None;
    }
    Some(JobLine {
        expr: tokens[..schedule_fields].join(" "),
        user: has_user_field.then(|| tokens[schedule_fields].to_string()),
        command: command.to_string(),
    })
}

/// The schedule half of a crontab line.
fn render_schedule(schedule: &ScheduleType) -> Result<String> {
    match schedule {
        ScheduleType::Cron(expr) => {
            let normalised = expr.split_whitespace().collect::<Vec<_>>().join(" ");
            if normalised.is_empty() {
                return Err(Error::Validation("schedule must not be empty".into()));
            }
            if normalised.starts_with('@') {
                if !CRON_ALIASES.contains(&normalised.to_ascii_lowercase().as_str()) {
                    return Err(Error::Validation(format!(
                        "`{normalised}` is not a cron shorthand; expected one of {}",
                        CRON_ALIASES.join(", ")
                    )));
                }
                // croner has no opinion on `@reboot` — there is no next
                // occurrence to compute — so it is accepted by name.
                if !normalised.eq_ignore_ascii_case("@reboot") {
                    validate_cron_expression(&normalised)?;
                }
                return Ok(normalised);
            }
            validate_cron_expression(&normalised)?;
            Ok(normalised)
        }
        ScheduleType::Calendar(text) => {
            let alias = text.trim().to_ascii_lowercase();
            if !CRON_ALIASES.contains(&alias.as_str()) {
                return Err(Error::Validation(format!(
                    "cron cannot express `{text}`: give five cron fields or one of {}",
                    CRON_ALIASES.join(", ")
                )));
            }
            Ok(alias)
        }
        ScheduleType::Interval(interval) => interval_to_cron(*interval),
        ScheduleType::OneShot(_) => Err(unsupported(
            "",
            "cron only runs recurring jobs; use `at` for a one-shot",
        )),
    }
}

fn validate_cron_expression(expr: &str) -> Result<()> {
    croner::Cron::new(expr)
        .parse()
        .map(|_| ())
        .map_err(|err| Error::Validation(format!("`{expr}` is not a valid cron expression: {err}")))
}

/// The only intervals cron can say exactly. Anything else (`7m`, `5h`,
/// `2d`) would drift at the top of every hour, day, or month, so it is
/// refused rather than approximated.
fn interval_to_cron(interval: Duration) -> Result<String> {
    let secs = interval.as_secs();
    let reject = || {
        Err(Error::Validation(format!(
            "cron cannot repeat every {secs}s: use a whole number of minutes dividing 60, \
             of hours dividing 24, or exactly 1 day"
        )))
    };
    if secs == 0 || !secs.is_multiple_of(60) {
        return reject();
    }
    let minutes = secs / 60;
    if minutes < 60 && 60u64.is_multiple_of(minutes) {
        return Ok(format!("*/{minutes} * * * *"));
    }
    if minutes.is_multiple_of(60) {
        let hours = minutes / 60;
        if hours < 24 && 24u64.is_multiple_of(hours) {
            return Ok(format!("0 */{hours} * * *"));
        }
        if hours == 24 {
            return Ok("0 0 * * *".to_string());
        }
    }
    reject()
}

/// One crontab line, ready to append or replace.
///
/// `has_user_field` picks the layout: `/etc/crontab` and `/etc/cron.d/*`
/// carry the user between the schedule and the command, a per-user
/// crontab does not.
pub fn render_line(
    schedule: &ScheduleType,
    user: Option<&str>,
    command: &str,
    has_user_field: bool,
) -> Result<String> {
    validate_command(command)?;
    let expr = render_schedule(schedule)?;
    if !has_user_field {
        return Ok(format!("{expr} {}", command.trim()));
    }
    let user = user.ok_or_else(|| {
        Error::Validation("a system crontab line needs the user to run the job as".into())
    })?;
    if !shell_safe_username(user) {
        return Err(Error::Validation(format!("invalid user name: {user}")));
    }
    Ok(format!("{expr} {user} {}", command.trim()))
}

fn decorate(body: &str, enabled: bool) -> String {
    if enabled {
        body.to_string()
    } else {
        format!("{DISABLED_MARKER}{body}")
    }
}

/// `crontab -l`, addressed at whoever owns the crontab.
fn list_cmd(user: &str, privilege: Privilege) -> String {
    match privilege {
        Privilege::User => "crontab -l".to_string(),
        // cronie wants `-u` before the operation.
        Privilege::Root => format!("crontab -l -u {user}"),
    }
}

fn install_cmd(user: &str, privilege: Privilege) -> String {
    match privilege {
        Privilege::User => "crontab -".to_string(),
        Privilege::Root => format!("crontab -u {user} -"),
    }
}

fn remove_cmd(user: &str, privilege: Privilege) -> String {
    match privilege {
        Privilege::User => "crontab -r".to_string(),
        Privilege::Root => format!("crontab -u {user} -r"),
    }
}

/// Whether anything worth keeping is left: a job line (disabled or not)
/// or an environment assignment. Bare comments do not count, so a
/// crontab that is nothing but cronie's banner is treated as empty.
fn has_content(file: &LineFile) -> bool {
    file.lines().iter().any(|line| {
        let trimmed = line.trim();
        if trimmed.is_empty() {
            return false;
        }
        match strip_disabled_marker(trimmed) {
            Some(payload) => !payload.trim().is_empty(),
            None => !trimmed.starts_with('#'),
        }
    })
}

/// Whether any line still describes a job, disabled ones included.
fn has_job_lines(file: &LineFile, has_user_field: bool) -> bool {
    file.lines().iter().any(|line| {
        let trimmed = line.trim();
        let payload = strip_disabled_marker(trimmed).unwrap_or(trimmed);
        parse_job_line(payload, has_user_field).is_some()
    })
}

/// Whether we created this file, and may therefore delete it.
fn is_managed(text: &str) -> bool {
    text.lines().any(|line| line.trim_end() == MANAGED_MARKER)
}

/// A location the operator may point a system cron job at.
fn validate_system_location(path: &str) -> Result<()> {
    if path == "/etc/crontab" {
        return Ok(());
    }
    // A run-parts directory holds scripts, not crontab lines: a job
    // written there would never run and would look like a broken script.
    if matches!(parse_cron_id(path), Ok(CronId::RunParts { .. })) {
        return Err(CronWriter::run_parts_unsupported(path, path, "write"));
    }
    if let Some(name) = path.strip_prefix("/etc/cron.d/") {
        if !name.is_empty() && !name.contains('/') {
            return Ok(());
        }
    }
    Err(Error::Validation(format!(
        "`{path}` is not a system crontab: expected /etc/crontab or a file in /etc/cron.d"
    )))
}

/// Where a spec's job belongs.
#[derive(Debug, Clone, PartialEq, Eq)]
enum Target {
    /// A crontab owned by `user`, reached only through the `crontab` binary.
    User { user: String, privilege: Privilege },
    /// `/etc/crontab` or `/etc/cron.d/<name>`.
    File { path: String },
}

/// Creates, edits, and removes cron jobs on one [`Host`].
pub struct CronWriter {
    host: Arc<dyn Host>,
}

impl CronWriter {
    pub fn new(host: Arc<dyn Host>) -> Self {
        Self { host }
    }

    /// Editing your own crontab is unprivileged; anyone else's is not,
    /// because `crontab -u` is root-only on both cronie and Vixie.
    fn privilege_for(&self, user: &str) -> Result<Privilege> {
        let current = self.host.current_user()?;
        Ok(if user == current {
            Privilege::User
        } else {
            Privilege::Root
        })
    }

    fn target_for(&self, spec: &JobSpec) -> Result<Target> {
        match spec.scope {
            JobScope::User => {
                let user = match spec.user.as_deref() {
                    Some(user) => user.to_string(),
                    None => self.host.current_user()?,
                };
                if !shell_safe_username(&user) {
                    return Err(Error::Validation(format!("invalid user name: {user}")));
                }
                let privilege = self.privilege_for(&user)?;
                Ok(Target::User { user, privilege })
            }
            JobScope::System => {
                if self.host.os()? == HostOs::MacOs {
                    return Err(unsupported(
                        "",
                        "macOS has no system crontab worth writing; use launchd",
                    ));
                }
                let path = match spec.location.as_deref() {
                    Some(location) => {
                        validate_system_location(location)?;
                        location.to_string()
                    }
                    None => {
                        let name = spec.name.as_deref().ok_or_else(|| {
                            Error::Validation(
                                "a system cron job needs a name: it becomes /etc/cron.d/<name>"
                                    .into(),
                            )
                        })?;
                        validate_simple_name(name, NameKind::CronD)?;
                        format!("/etc/cron.d/{name}")
                    }
                };
                Ok(Target::File { path })
            }
        }
    }

    /// `crontab -l`, with "you have no crontab" told apart from failure.
    fn read_user_crontab(&self, user: &str, privilege: Privilege) -> Result<String> {
        let cmd = list_cmd(user, privilege);
        let output = self.host.run(&cmd, None, privilege)?;
        if output.success() {
            return Ok(output.stdout_str().into_owned());
        }
        // Both implementations exit 1 with "no crontab for <user>" when
        // the spool file is simply absent, which is not an error here.
        if output.code == Some(1) && output.stderr.to_ascii_lowercase().contains("no crontab") {
            return Ok(String::new());
        }
        output.require_success(&cmd).map(|_| String::new())
    }

    /// Read `path`, refusing to edit a file that is no longer there.
    fn read_system_file(&self, path: &str) -> Result<String> {
        self.host
            .read_to_string(path, Privilege::Root)?
            .ok_or_else(|| {
                Error::Conflict(format!(
                    "{path} is gone; it changed since it was read, refresh and retry"
                ))
            })
    }

    /// The line the id points at, and what it parses to. Anything that
    /// is not a job any more is drift, not a target.
    fn job_line_at(
        file: &LineFile,
        line: usize,
        has_user_field: bool,
        id: &str,
    ) -> Result<(String, JobLine)> {
        let raw = file.line(line).ok_or_else(|| drifted(id))?.to_string();
        let trimmed = raw.trim();
        let payload = strip_disabled_marker(trimmed).unwrap_or(trimmed);
        let parsed = parse_job_line(payload, has_user_field).ok_or_else(|| drifted(id))?;
        Ok((raw, parsed))
    }

    /// The install step for a per-user crontab: the whole file on stdin,
    /// minus the banner `crontab -l` added for us.
    fn install_change(user: &str, privilege: Privilege, file: &LineFile) -> Change {
        Change::Command {
            cmd: install_cmd(user, privilege),
            stdin: Some(strip_install_header(&file.render())),
            privilege,
            description: format!("install {user}'s crontab"),
            on_fail: FailPolicy::Error,
        }
    }

    /// Find the job we just wrote in a fresh `crontab -l`, so the id we
    /// report is the one `list` will show.
    fn resolve_user_id(
        &self,
        user: &str,
        privilege: Privilege,
        body: &str,
    ) -> Result<Option<String>> {
        let Some(want) = parse_job_line(body, false) else {
            return Ok(None);
        };
        let text = self.read_user_crontab(user, privilege)?;
        let tasks = CronAdapter::parse_crontab(&text, &format!("user:{user}"), false);
        let mut hits = tasks.into_iter().filter(|task| {
            task.command == want.command
                && matches!(&task.schedule, ScheduleType::Cron(expr) if *expr == want.expr)
        });
        let first = hits.next();
        match (first, hits.next()) {
            (Some(task), None) => Ok(Some(task.id)),
            _ => Ok(None),
        }
    }

    /// Per-user ids are only knowable after the fact. In a dry run we
    /// report the line the append landed on and say so.
    fn settle_user_id(
        &self,
        outcome: &mut MutationOutcome,
        user: &str,
        privilege: Privilege,
        body: &str,
        mode: ApplyMode,
        guess_line: usize,
    ) {
        let guess = format!("user:{user}:{guess_line}");
        if mode == ApplyMode::DryRun {
            outcome.id = Some(guess);
            outcome
                .notes
                .push("dry run: the id is a guess until the crontab is re-read".to_string());
            return;
        }
        match self.resolve_user_id(user, privilege, body) {
            Ok(Some(id)) => outcome.id = Some(id),
            Ok(None) => {
                outcome.id = Some(guess);
                outcome.notes.push(
                    "could not pick this job out of the crontab uniquely; the reported id may be \
                     off by a line"
                        .to_string(),
                );
            }
            Err(err) => {
                outcome.id = Some(guess);
                outcome.notes.push(format!(
                    "could not re-read the crontab to confirm the id: {err}"
                ));
            }
        }
    }

    fn run_parts_unsupported(id: &str, path: &str, verb: &str) -> Error {
        unsupported(
            id,
            &format!(
                "{path} is a run-parts script, not a crontab entry: {verb} the script itself, \
                 or keep the job in /etc/cron.d instead"
            ),
        )
    }

    /// Comment a line out, or restore it. Already being in the requested
    /// state is a no-op with a note, not an error.
    fn toggle(
        file: &mut LineFile,
        line: usize,
        enabled: bool,
        has_user_field: bool,
        id: &str,
    ) -> Result<Option<String>> {
        let raw = file.line(line).ok_or_else(|| drifted(id))?.to_string();
        let is_disabled = strip_disabled_marker(&raw).is_some();
        if enabled != is_disabled {
            return Ok(Some(format!(
                "{id} is already {}",
                if enabled { "enabled" } else { "disabled" }
            )));
        }
        if enabled {
            file.uncomment(line, DISABLED_MARKER)?;
        } else {
            let trimmed = raw.trim();
            parse_job_line(trimmed, has_user_field).ok_or_else(|| drifted(id))?;
            file.comment_out(line, &raw, DISABLED_MARKER)?;
        }
        Ok(None)
    }
}

impl JobWriter for CronWriter {
    fn kind(&self) -> TaskSourceKind {
        TaskSourceKind::Cron
    }

    fn create(&self, spec: &JobSpec, mode: ApplyMode) -> Result<MutationOutcome> {
        spec.validate()?;
        let notes: Vec<String> = percent_note(&spec.command).into_iter().collect();
        match self.target_for(spec)? {
            Target::User { user, privilege } => {
                let body = render_line(&spec.schedule, None, &spec.command, false)?;
                let text = self.read_user_crontab(&user, privilege)?;
                let mut file = LineFile::parse(&text);
                let line = file.append(&decorate(&body, spec.enabled));
                let change = Self::install_change(&user, privilege, &file);
                let mut outcome = execute(&*self.host, vec![change], mode)?;
                outcome.notes.extend(notes);
                self.settle_user_id(&mut outcome, &user, privilege, &body, mode, line);
                Ok(outcome)
            }
            Target::File { path } => {
                let user = spec.user.clone().unwrap_or_else(|| "root".to_string());
                let body = render_line(&spec.schedule, Some(&user), &spec.command, true)?;
                let line = decorate(&body, spec.enabled);
                let before = self.host.read_to_string(&path, Privilege::Root)?;
                let (after, number) = match &before {
                    // A file we create says so on line 1, so delete can
                    // tell later whether removing it is ours to do.
                    None => (format!("{MANAGED_MARKER}\n{line}\n"), 2),
                    Some(text) => {
                        let mut file = LineFile::parse(text);
                        let number = file.append(&line);
                        (file.render(), number)
                    }
                };
                let change = Change::WriteFile {
                    path: path.clone(),
                    before,
                    after,
                    mode: 0o644,
                    privilege: Privilege::Root,
                };
                let mut outcome = execute(&*self.host, vec![change], mode)?;
                outcome.notes.extend(notes);
                outcome.id = Some(format!("{path}:{number}"));
                Ok(outcome)
            }
        }
    }

    fn update(&self, id: &str, spec: &JobSpec, mode: ApplyMode) -> Result<MutationOutcome> {
        spec.validate()?;
        let notes: Vec<String> = percent_note(&spec.command).into_iter().collect();
        match parse_cron_id(id)? {
            CronId::RunParts { path } => Err(Self::run_parts_unsupported(id, &path, "edit")),
            CronId::UserCrontab { user, line } => {
                let privilege = self.privilege_for(&user)?;
                let text = self.read_user_crontab(&user, privilege)?;
                let mut file = LineFile::parse(&text);
                let (raw, _) = Self::job_line_at(&file, line, false, id)?;
                let body = render_line(&spec.schedule, None, &spec.command, false)?;
                file.replace(line, &raw, &decorate(&body, spec.enabled))?;
                let change = Self::install_change(&user, privilege, &file);
                let mut outcome = execute(&*self.host, vec![change], mode)?;
                outcome.notes.extend(notes);
                self.settle_user_id(&mut outcome, &user, privilege, &body, mode, line);
                Ok(outcome)
            }
            CronId::SystemFile { path, line } => {
                let before = self.read_system_file(&path)?;
                let mut file = LineFile::parse(&before);
                let (raw, current) = Self::job_line_at(&file, line, true, id)?;
                // The user column stays as it was unless the caller
                // asked for a different one.
                let user = spec
                    .user
                    .clone()
                    .or(current.user)
                    .unwrap_or_else(|| "root".to_string());
                let body = render_line(&spec.schedule, Some(&user), &spec.command, true)?;
                file.replace(line, &raw, &decorate(&body, spec.enabled))?;
                let change = Change::WriteFile {
                    path: path.clone(),
                    before: Some(before),
                    after: file.render(),
                    mode: 0o644,
                    privilege: Privilege::Root,
                };
                let mut outcome = execute(&*self.host, vec![change], mode)?;
                outcome.notes.extend(notes);
                outcome.id = Some(format!("{path}:{line}"));
                Ok(outcome)
            }
        }
    }

    fn delete(&self, id: &str, mode: ApplyMode) -> Result<MutationOutcome> {
        match parse_cron_id(id)? {
            CronId::RunParts { path } => {
                let before = self.host.read_to_string(&path, Privilege::Root)?;
                let change = Change::RemoveFile {
                    path,
                    before,
                    privilege: Privilege::Root,
                };
                let mut outcome = execute(&*self.host, vec![change], mode)?;
                outcome.id = Some(id.to_string());
                Ok(outcome)
            }
            CronId::UserCrontab { user, line } => {
                let privilege = self.privilege_for(&user)?;
                let text = self.read_user_crontab(&user, privilege)?;
                let mut file = LineFile::parse(&text);
                let (raw, _) = Self::job_line_at(&file, line, false, id)?;
                file.delete(line, &raw)?;
                // `crontab -` rejects an empty file, and leaving cronie's
                // banner behind would resurrect an empty crontab, so a
                // crontab with nothing left in it is removed outright.
                let change = if has_content(&file) {
                    Self::install_change(&user, privilege, &file)
                } else {
                    Change::Command {
                        cmd: remove_cmd(&user, privilege),
                        stdin: None,
                        privilege,
                        description: format!("remove {user}'s now-empty crontab"),
                        on_fail: FailPolicy::Error,
                    }
                };
                let mut outcome = execute(&*self.host, vec![change], mode)?;
                outcome.id = Some(id.to_string());
                Ok(outcome)
            }
            CronId::SystemFile { path, line } => {
                let before = self.read_system_file(&path)?;
                let mut file = LineFile::parse(&before);
                let (raw, _) = Self::job_line_at(&file, line, true, id)?;
                file.delete(line, &raw)?;
                let change = if is_managed(&before) && !has_job_lines(&file, true) {
                    Change::RemoveFile {
                        path: path.clone(),
                        before: Some(before),
                        privilege: Privilege::Root,
                    }
                } else {
                    Change::WriteFile {
                        path: path.clone(),
                        before: Some(before),
                        after: file.render(),
                        mode: 0o644,
                        privilege: Privilege::Root,
                    }
                };
                let mut outcome = execute(&*self.host, vec![change], mode)?;
                outcome.id = Some(id.to_string());
                Ok(outcome)
            }
        }
    }

    fn set_enabled(&self, id: &str, enabled: bool, mode: ApplyMode) -> Result<MutationOutcome> {
        match parse_cron_id(id)? {
            CronId::RunParts { path } => {
                // run-parts runs whatever is executable, so the mode bit
                // is the enable switch.
                let change = Change::Command {
                    cmd: format!(
                        "chmod {} {}",
                        if enabled { "a+x" } else { "a-x" },
                        shell_quote(&path)
                    ),
                    stdin: None,
                    privilege: Privilege::Root,
                    description: format!(
                        "{} {path}",
                        if enabled {
                            "make executable:"
                        } else {
                            "clear the executable bit on"
                        }
                    ),
                    on_fail: FailPolicy::Error,
                };
                let mut outcome = execute(&*self.host, vec![change], mode)?;
                outcome.id = Some(id.to_string());
                Ok(outcome)
            }
            CronId::UserCrontab { user, line } => {
                let privilege = self.privilege_for(&user)?;
                let text = self.read_user_crontab(&user, privilege)?;
                let mut file = LineFile::parse(&text);
                let note = Self::toggle(&mut file, line, enabled, false, id)?;
                let changes = match &note {
                    Some(_) => Vec::new(),
                    None => vec![Self::install_change(&user, privilege, &file)],
                };
                let mut outcome = execute(&*self.host, changes, mode)?;
                outcome.notes.extend(note);
                outcome.id = Some(id.to_string());
                Ok(outcome)
            }
            CronId::SystemFile { path, line } => {
                let before = self.read_system_file(&path)?;
                let mut file = LineFile::parse(&before);
                let note = Self::toggle(&mut file, line, enabled, true, id)?;
                let changes = match &note {
                    Some(_) => Vec::new(),
                    None => vec![Change::WriteFile {
                        path: path.clone(),
                        before: Some(before),
                        after: file.render(),
                        mode: 0o644,
                        privilege: Privilege::Root,
                    }],
                };
                let mut outcome = execute(&*self.host, changes, mode)?;
                outcome.notes.extend(note);
                outcome.id = Some(id.to_string());
                Ok(outcome)
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use shuvjobs_core::host::fake::Call;
    use shuvjobs_core::host::{FakeHost, PrivilegePolicy};

    /// What cronie's `crontab -l` actually prints: three banner lines we
    /// must never feed back, then the operator's own content.
    const BANNER: &str = "\
# DO NOT EDIT THIS FILE - edit the master and reinstall.
# (/tmp/crontab.QcXyZ installed on Mon Jan  1 00:00:00 2024)
# (Cron version -- $Id: crontab.c,v 2.13 2019/01/01 00:00:00 root Exp $)
";

    fn sudoer() -> PrivilegePolicy {
        PrivilegePolicy {
            is_root: false,
            sudo: true,
        }
    }

    fn writer(host: &Arc<FakeHost>) -> CronWriter {
        CronWriter::new(Arc::clone(host) as Arc<dyn Host>)
    }

    fn spec(expr: &str, command: &str) -> JobSpec {
        JobSpec::new(
            TaskSourceKind::Cron,
            ScheduleType::Cron(expr.to_string()),
            command.to_string(),
        )
    }

    fn system_spec(name: &str, expr: &str, command: &str) -> JobSpec {
        let mut spec = spec(expr, command);
        spec.scope = JobScope::System;
        spec.name = Some(name.to_string());
        spec
    }

    fn call(cmd: &str, stdin: Option<&str>, privilege: Privilege) -> Call {
        Call {
            cmd: cmd.to_string(),
            stdin: stdin.map(|s| s.as_bytes().to_vec()),
            privilege,
        }
    }

    fn stdin_of(host: &FakeHost, cmd: &str) -> String {
        let call = host
            .calls()
            .into_iter()
            .find(|call| call.cmd == cmd)
            .unwrap_or_else(|| panic!("`{cmd}` was never run: {:?}", host.calls()));
        String::from_utf8(call.stdin.expect("command had no stdin")).expect("stdin is utf-8")
    }

    // -- render_line -----------------------------------------------------

    #[test]
    fn a_user_line_is_schedule_then_command_and_a_system_line_adds_the_user() {
        assert_eq!(
            render_line(
                &ScheduleType::Cron("  0   9  *  * 1-5 ".into()),
                None,
                "/usr/local/bin/report",
                false
            )
            .unwrap(),
            "0 9 * * 1-5 /usr/local/bin/report"
        );
        assert_eq!(
            render_line(
                &ScheduleType::Cron("0 9 * * *".into()),
                Some("nobody"),
                "/usr/local/bin/report",
                true
            )
            .unwrap(),
            "0 9 * * * nobody /usr/local/bin/report"
        );
    }

    #[test]
    fn reboot_skips_validation_and_other_shorthands_pass_through() {
        assert_eq!(
            render_line(&ScheduleType::Cron("@reboot".into()), None, "warm", false).unwrap(),
            "@reboot warm"
        );
        assert_eq!(
            render_line(
                &ScheduleType::Calendar("@daily".into()),
                None,
                "warm",
                false
            )
            .unwrap(),
            "@daily warm"
        );
        for bad in ["@fortnightly", "Mon *-*-* 09:00:00"] {
            let err =
                render_line(&ScheduleType::Calendar(bad.into()), None, "x", false).expect_err(bad);
            assert!(matches!(err, Error::Validation(_)), "{bad}: {err:?}");
        }
    }

    #[test]
    fn a_nonsense_expression_is_a_validation_error() {
        for bad in ["0 99 * * *", "* * * *", "not a schedule at all", "@"] {
            let err =
                render_line(&ScheduleType::Cron(bad.into()), None, "x", false).expect_err(bad);
            assert!(matches!(err, Error::Validation(_)), "{bad}: {err:?}");
        }
    }

    #[test]
    fn intervals_map_only_onto_expressions_cron_can_say_exactly() {
        let render = |secs: u64| {
            render_line(
                &ScheduleType::Interval(Duration::from_secs(secs)),
                None,
                "x",
                false,
            )
        };
        for (secs, expected) in [
            (60, "*/1 * * * * x"),
            (300, "*/5 * * * * x"),
            (900, "*/15 * * * * x"),
            (1_800, "*/30 * * * * x"),
            (3_600, "0 */1 * * * x"),
            (7_200, "0 */2 * * * x"),
            (43_200, "0 */12 * * * x"),
            (86_400, "0 0 * * * x"),
        ] {
            assert_eq!(render(secs).unwrap(), expected, "{secs}s");
        }
        for secs in [0, 45, 420, 18_000, 172_800] {
            let err = render(secs).expect_err(&format!("{secs}s"));
            assert!(matches!(err, Error::Validation(_)), "{secs}s: {err:?}");
        }
    }

    #[test]
    fn a_one_shot_belongs_to_at_not_cron() {
        let err = render_line(&ScheduleType::OneShot(chrono::Utc::now()), None, "x", false)
            .expect_err("must refuse");
        match err {
            Error::Unsupported { reason, .. } => assert!(reason.contains("at"), "{reason}"),
            other => panic!("expected Unsupported, got {other:?}"),
        }
    }

    // -- strip_install_header --------------------------------------------

    #[test]
    fn the_install_banner_is_dropped_but_the_operators_comments_are_not() {
        assert_eq!(
            strip_install_header(&format!("{BANNER}# mine\n0 9 * * * x\n")),
            "# mine\n0 9 * * * x\n"
        );
        assert_eq!(
            strip_install_header("# mine\n0 9 * * * x\n"),
            "# mine\n0 9 * * * x\n"
        );
        assert_eq!(strip_install_header(""), "");
        // Only from the top, and only three lines' worth.
        let doubled = format!("{BANNER}{BANNER}0 9 * * * x\n");
        assert_eq!(
            strip_install_header(&doubled),
            format!("{BANNER}0 9 * * * x\n")
        );
    }

    // -- create ----------------------------------------------------------

    #[test]
    fn creating_a_per_user_job_appends_and_reinstalls_without_the_banner() {
        let before = format!("{BANNER}MAILTO=ops\n0 9 * * * /usr/local/bin/report\n");
        let after = format!("{before}*/5 * * * * echo hi\n");
        let host = Arc::new(
            FakeHost::new()
                .script("crontab -l", 0, &before, "")
                .then_script("crontab -l", 0, &after, "")
                .script("crontab -", 0, "", ""),
        );
        let outcome = writer(&host)
            .create(&spec("*/5 * * * *", "echo hi"), ApplyMode::Apply)
            .unwrap();

        assert!(outcome.applied);
        assert_eq!(outcome.id.as_deref(), Some("user:tester:6"));
        assert_eq!(
            host.calls(),
            vec![
                call("crontab -l", None, Privilege::User),
                call(
                    "crontab -",
                    Some("MAILTO=ops\n0 9 * * * /usr/local/bin/report\n*/5 * * * * echo hi\n"),
                    Privilege::User,
                ),
                call("crontab -l", None, Privilege::User),
            ]
        );
        assert!(stdin_of(&host, "crontab -").ends_with('\n'));
    }

    #[test]
    fn an_absent_crontab_reads_as_empty() {
        let host = Arc::new(
            FakeHost::new()
                .script("crontab -l", 1, "", "no crontab for tester\n")
                .script("crontab -", 0, "", ""),
        );
        writer(&host)
            .create(&spec("@daily", "echo hi"), ApplyMode::Apply)
            .unwrap();
        assert_eq!(stdin_of(&host, "crontab -"), "@daily echo hi\n");
    }

    #[test]
    fn a_crontab_that_fails_for_any_other_reason_is_an_error() {
        let host = Arc::new(FakeHost::new().script("crontab -l", 1, "", "permission denied\n"));
        let err = writer(&host)
            .create(&spec("@daily", "echo hi"), ApplyMode::Apply)
            .expect_err("must fail");
        assert!(matches!(err, Error::Command { .. }), "got {err:?}");
    }

    #[test]
    fn another_users_crontab_goes_through_dash_u_as_root() {
        let mut job = spec("@daily", "echo hi");
        job.user = Some("alice".to_string());
        let host = Arc::new(
            FakeHost::new()
                .with_policy(sudoer())
                .script("crontab -l -u alice", 0, "", "")
                .then_script("crontab -l -u alice", 0, "@daily echo hi\n", "")
                .script("crontab -u alice -", 0, "", ""),
        );
        let outcome = writer(&host).create(&job, ApplyMode::Apply).unwrap();
        assert_eq!(outcome.id.as_deref(), Some("user:alice:1"));
        assert_eq!(
            host.calls(),
            vec![
                call("crontab -l -u alice", None, Privilege::Root),
                call(
                    "crontab -u alice -",
                    Some("@daily echo hi\n"),
                    Privilege::Root
                ),
                call("crontab -l -u alice", None, Privilege::Root),
            ]
        );
    }

    #[test]
    fn a_dry_run_reads_but_never_installs_and_says_the_id_is_a_guess() {
        let host = Arc::new(FakeHost::new().script("crontab -l", 0, "0 9 * * * old\n", ""));
        let outcome = writer(&host)
            .create(&spec("@daily", "echo hi"), ApplyMode::DryRun)
            .unwrap();
        assert!(!outcome.applied);
        assert_eq!(outcome.id.as_deref(), Some("user:tester:2"));
        assert!(outcome.notes.iter().any(|note| note.contains("dry run")));
        assert_eq!(host.calls().len(), 1);
    }

    #[test]
    fn creating_a_system_job_writes_a_marked_cron_d_file_as_root() {
        let host = Arc::new(FakeHost::new().with_policy(sudoer()).root_only("/etc/"));
        let outcome = writer(&host)
            .create(
                &system_spec("metrics", "*/5 * * * *", "/usr/local/bin/metrics"),
                ApplyMode::Apply,
            )
            .unwrap();

        assert_eq!(outcome.id.as_deref(), Some("/etc/cron.d/metrics:2"));
        assert_eq!(
            host.file_contents("/etc/cron.d/metrics").as_deref(),
            Some("# managed by shuvjobs\n*/5 * * * * root /usr/local/bin/metrics\n")
        );
        assert_eq!(host.file_mode("/etc/cron.d/metrics"), Some(0o644));
        assert!(host.calls().is_empty());
        match &outcome.changes[0] {
            Change::WriteFile {
                before, privilege, ..
            } => {
                assert_eq!(*before, None);
                assert_eq!(*privilege, Privilege::Root);
            }
            other => panic!("expected a file write, got {other:?}"),
        }
    }

    #[test]
    fn appending_to_an_existing_cron_d_file_keeps_it_byte_for_byte() {
        let before = "# managed by puppet\n17 *\t* * *\troot\tcd / && tidy\n";
        let host = Arc::new(
            FakeHost::new()
                .with_policy(sudoer())
                .root_only("/etc/")
                .file("/etc/cron.d/metrics", before),
        );
        let mut job = system_spec("metrics", "@daily", "/usr/local/bin/metrics");
        job.user = Some("nobody".to_string());
        let outcome = writer(&host).create(&job, ApplyMode::Apply).unwrap();
        assert_eq!(outcome.id.as_deref(), Some("/etc/cron.d/metrics:3"));
        assert_eq!(
            host.file_contents("/etc/cron.d/metrics").as_deref(),
            Some(&*format!("{before}@daily nobody /usr/local/bin/metrics\n"))
        );
    }

    #[test]
    fn a_system_job_without_sudo_asks_for_root_up_front() {
        let host = Arc::new(FakeHost::new().root_only("/etc/"));
        let err = writer(&host)
            .create(
                &system_spec("metrics", "@daily", "/usr/local/bin/metrics"),
                ApplyMode::Apply,
            )
            .expect_err("must refuse");
        assert!(matches!(err, Error::NeedsRoot { .. }), "got {err:?}");
        assert_eq!(host.file_contents("/etc/cron.d/metrics"), None);
    }

    #[test]
    fn a_system_job_needs_a_name_or_a_system_location() {
        let host = Arc::new(FakeHost::new().with_policy(sudoer()).root_only("/etc/"));
        let mut job = spec("@daily", "x");
        job.scope = JobScope::System;
        assert!(matches!(
            writer(&host).create(&job, ApplyMode::DryRun),
            Err(Error::Validation(_))
        ));

        job.location = Some("/home/tester/crontab".to_string());
        assert!(matches!(
            writer(&host).create(&job, ApplyMode::DryRun),
            Err(Error::Validation(_))
        ));

        job.location = Some("/etc/crontab".to_string());
        let outcome = writer(&host).create(&job, ApplyMode::DryRun).unwrap();
        assert_eq!(outcome.id.as_deref(), Some("/etc/crontab:2"));
    }

    #[test]
    fn a_run_parts_directory_is_not_a_place_for_a_crontab_line() {
        let host = Arc::new(FakeHost::new().with_policy(sudoer()).root_only("/etc/"));
        let mut job = spec("@daily", "x");
        job.scope = JobScope::System;
        job.location = Some("/etc/cron.daily/backup".to_string());
        match writer(&host).create(&job, ApplyMode::DryRun) {
            Err(Error::Unsupported { reason, .. }) => {
                assert!(reason.contains("cron.d"), "{reason}")
            }
            other => panic!("expected Unsupported, got {other:?}"),
        }
    }

    #[test]
    fn macos_has_no_system_crontab_to_write() {
        let host = Arc::new(
            FakeHost::new()
                .with_policy(sudoer())
                .with_os(shuvjobs_core::host::HostOs::MacOs),
        );
        match writer(&host).create(
            &system_spec("metrics", "@daily", "/usr/local/bin/metrics"),
            ApplyMode::DryRun,
        ) {
            Err(Error::Unsupported { reason, .. }) => {
                assert!(reason.contains("launchd"), "{reason}")
            }
            other => panic!("expected Unsupported, got {other:?}"),
        }
        // The per-user crontab is still fine on macOS.
        let host = Arc::new(
            FakeHost::new()
                .with_os(shuvjobs_core::host::HostOs::MacOs)
                .script("crontab -l", 0, "", ""),
        );
        writer(&host)
            .create(&spec("@daily", "echo hi"), ApplyMode::DryRun)
            .unwrap();
    }

    #[test]
    fn a_percent_in_the_command_is_written_but_flagged() {
        let host = Arc::new(FakeHost::new().script("crontab -l", 0, "", ""));
        let outcome = writer(&host)
            .create(&spec("@daily", "echo $(date +%F)"), ApplyMode::DryRun)
            .unwrap();
        assert!(
            outcome.notes.iter().any(|note| note.contains('%')),
            "{:?}",
            outcome.notes
        );
        let quiet = writer(&host)
            .create(&spec("@daily", r"echo $(date +\%F)"), ApplyMode::DryRun)
            .unwrap();
        assert!(
            !quiet.notes.iter().any(|note| note.contains("stdin")),
            "{:?}",
            quiet.notes
        );
    }

    #[test]
    fn a_disabled_job_is_created_behind_the_marker() {
        let host = Arc::new(FakeHost::new().script("crontab -l", 0, "", "").script(
            "crontab -",
            0,
            "",
            "",
        ));
        let mut job = spec("@daily", "echo hi");
        job.enabled = false;
        writer(&host).create(&job, ApplyMode::Apply).unwrap();
        assert_eq!(
            stdin_of(&host, "crontab -"),
            "#shuvjobs-disabled# @daily echo hi\n"
        );
    }

    // -- update ----------------------------------------------------------

    const CRON_D: &str = "\
# managed by puppet
17 *\t* * *\troot\tcd / && tidy

*/5 * * * * nobody /usr/local/bin/metrics --batch
";

    #[test]
    fn updating_a_system_line_leaves_every_other_byte_alone() {
        let host = Arc::new(
            FakeHost::new()
                .with_policy(sudoer())
                .root_only("/etc/")
                .file("/etc/cron.d/metrics", CRON_D),
        );
        let outcome = writer(&host)
            .update(
                "/etc/cron.d/metrics:4",
                &spec("0 3 * * *", "/usr/local/bin/metrics --full"),
                ApplyMode::Apply,
            )
            .unwrap();
        assert_eq!(outcome.id.as_deref(), Some("/etc/cron.d/metrics:4"));
        assert_eq!(
            host.file_contents("/etc/cron.d/metrics").as_deref(),
            Some(
                "# managed by puppet\n17 *\t* * *\troot\tcd / && tidy\n\n\
                 0 3 * * * nobody /usr/local/bin/metrics --full\n"
            )
        );
    }

    #[test]
    fn updating_can_hand_the_job_to_a_different_user() {
        let host = Arc::new(
            FakeHost::new()
                .with_policy(sudoer())
                .root_only("/etc/")
                .file("/etc/cron.d/metrics", CRON_D),
        );
        let mut job = spec("@daily", "/usr/local/bin/metrics");
        job.user = Some("ops".to_string());
        writer(&host)
            .update("/etc/cron.d/metrics:4", &job, ApplyMode::Apply)
            .unwrap();
        assert!(host
            .file_contents("/etc/cron.d/metrics")
            .unwrap()
            .contains("@daily ops /usr/local/bin/metrics\n"));
    }

    #[test]
    fn updating_a_job_that_is_no_longer_there_is_a_conflict() {
        let host = Arc::new(
            FakeHost::new()
                .with_policy(sudoer())
                .root_only("/etc/")
                .file("/etc/cron.d/metrics", CRON_D),
        );
        // Line 1 is a comment, line 9 is past the end, and the file
        // itself may be gone entirely.
        for id in ["/etc/cron.d/metrics:1", "/etc/cron.d/metrics:9"] {
            let err = writer(&host)
                .update(id, &spec("@daily", "x"), ApplyMode::Apply)
                .expect_err(id);
            assert!(matches!(err, Error::Conflict(_)), "{id}: {err:?}");
        }
        let err = writer(&host)
            .update("/etc/cron.d/gone:2", &spec("@daily", "x"), ApplyMode::Apply)
            .expect_err("must refuse");
        assert!(matches!(err, Error::Conflict(_)), "got {err:?}");
        assert_eq!(
            host.file_contents("/etc/cron.d/metrics").as_deref(),
            Some(CRON_D)
        );
    }

    #[test]
    fn updating_a_per_user_job_replaces_only_that_line() {
        let before = format!("{BANNER}MAILTO=ops\n0 9 * * * /usr/local/bin/report\n@daily other\n");
        let after =
            format!("{BANNER}MAILTO=ops\n0 3 * * * /usr/local/bin/report --full\n@daily other\n");
        let host = Arc::new(
            FakeHost::new()
                .script("crontab -l", 0, &before, "")
                .then_script("crontab -l", 0, &after, "")
                .script("crontab -", 0, "", ""),
        );
        let outcome = writer(&host)
            .update(
                "user:tester:5",
                &spec("0 3 * * *", "/usr/local/bin/report --full"),
                ApplyMode::Apply,
            )
            .unwrap();
        assert_eq!(outcome.id.as_deref(), Some("user:tester:5"));
        assert_eq!(
            stdin_of(&host, "crontab -"),
            "MAILTO=ops\n0 3 * * * /usr/local/bin/report --full\n@daily other\n"
        );
    }

    #[test]
    fn a_crlf_file_stays_crlf_through_an_update() {
        let before = "# managed by puppet\r\n0 9 * * * root /usr/local/bin/report\r\n";
        let host = Arc::new(
            FakeHost::new()
                .with_policy(sudoer())
                .root_only("/etc/")
                .file("/etc/cron.d/report", before),
        );
        writer(&host)
            .update(
                "/etc/cron.d/report:2",
                &spec("0 3 * * *", "/usr/local/bin/report"),
                ApplyMode::Apply,
            )
            .unwrap();
        assert_eq!(
            host.file_contents("/etc/cron.d/report").as_deref(),
            Some("# managed by puppet\r\n0 3 * * * root /usr/local/bin/report\r\n")
        );
    }

    #[test]
    fn a_run_parts_script_cannot_be_updated_in_place() {
        let host = Arc::new(FakeHost::new().with_policy(sudoer()).root_only("/etc/"));
        match writer(&host).update(
            "/etc/cron.daily/backup",
            &spec("@daily", "x"),
            ApplyMode::DryRun,
        ) {
            Err(Error::Unsupported { reason, .. }) => {
                assert!(reason.contains("cron.d"), "{reason}")
            }
            other => panic!("expected Unsupported, got {other:?}"),
        }
    }

    // -- delete ----------------------------------------------------------

    #[test]
    fn deleting_the_last_per_user_job_removes_the_crontab_outright() {
        let before = format!("{BANNER}0 9 * * * /usr/local/bin/report\n");
        let host = Arc::new(FakeHost::new().script("crontab -l", 0, &before, "").script(
            "crontab -r",
            0,
            "",
            "",
        ));
        let outcome = writer(&host)
            .delete("user:tester:4", ApplyMode::Apply)
            .unwrap();
        assert_eq!(outcome.id.as_deref(), Some("user:tester:4"));
        assert_eq!(
            host.calls(),
            vec![
                call("crontab -l", None, Privilege::User),
                call("crontab -r", None, Privilege::User),
            ]
        );
    }

    #[test]
    fn deleting_a_job_that_leaves_settings_behind_reinstalls_instead() {
        let before = format!("{BANNER}MAILTO=ops\n0 9 * * * /usr/local/bin/report\n");
        let host = Arc::new(FakeHost::new().script("crontab -l", 0, &before, "").script(
            "crontab -",
            0,
            "",
            "",
        ));
        writer(&host)
            .delete("user:tester:5", ApplyMode::Apply)
            .unwrap();
        assert_eq!(stdin_of(&host, "crontab -"), "MAILTO=ops\n");
    }

    #[test]
    fn deleting_another_users_job_needs_root() {
        let before = "0 9 * * * /usr/local/bin/report\n";
        let host = Arc::new(
            FakeHost::new()
                .with_policy(sudoer())
                .script("crontab -l -u alice", 0, before, "")
                .script("crontab -u alice -r", 0, "", ""),
        );
        writer(&host)
            .delete("user:alice:1", ApplyMode::Apply)
            .unwrap();
        assert_eq!(
            host.calls().last().unwrap(),
            &call("crontab -u alice -r", None, Privilege::Root)
        );
    }

    #[test]
    fn deleting_the_last_job_from_a_file_we_created_removes_the_file() {
        let host = Arc::new(
            FakeHost::new()
                .with_policy(sudoer())
                .root_only("/etc/")
                .file(
                    "/etc/cron.d/metrics",
                    "# managed by shuvjobs\n@daily root /usr/local/bin/metrics\n",
                ),
        );
        writer(&host)
            .delete("/etc/cron.d/metrics:2", ApplyMode::Apply)
            .unwrap();
        assert_eq!(host.file_contents("/etc/cron.d/metrics"), None);
    }

    #[test]
    fn deleting_from_a_file_we_did_not_create_only_drops_the_line() {
        let host = Arc::new(
            FakeHost::new()
                .with_policy(sudoer())
                .root_only("/etc/")
                .file("/etc/cron.d/metrics", CRON_D),
        );
        writer(&host)
            .delete("/etc/cron.d/metrics:4", ApplyMode::Apply)
            .unwrap();
        assert_eq!(
            host.file_contents("/etc/cron.d/metrics").as_deref(),
            Some("# managed by puppet\n17 *\t* * *\troot\tcd / && tidy\n\n")
        );
    }

    #[test]
    fn deleting_a_run_parts_script_removes_the_script() {
        let host = Arc::new(
            FakeHost::new()
                .with_policy(sudoer())
                .root_only("/etc/")
                .file("/etc/cron.daily/backup", "#!/bin/sh\nexit 0\n"),
        );
        let outcome = writer(&host)
            .delete("/etc/cron.daily/backup", ApplyMode::Apply)
            .unwrap();
        assert_eq!(host.file_contents("/etc/cron.daily/backup"), None);
        match &outcome.changes[0] {
            Change::RemoveFile {
                path,
                before,
                privilege,
            } => {
                assert_eq!(path, "/etc/cron.daily/backup");
                assert_eq!(before.as_deref(), Some("#!/bin/sh\nexit 0\n"));
                assert_eq!(*privilege, Privilege::Root);
            }
            other => panic!("expected a file removal, got {other:?}"),
        }
    }

    // -- set_enabled -----------------------------------------------------

    #[test]
    fn disabling_then_enabling_a_system_line_restores_the_exact_bytes() {
        let host = Arc::new(
            FakeHost::new()
                .with_policy(sudoer())
                .root_only("/etc/")
                .file("/etc/cron.d/metrics", CRON_D),
        );
        writer(&host)
            .set_enabled("/etc/cron.d/metrics:4", false, ApplyMode::Apply)
            .unwrap();
        assert_eq!(
            host.file_contents("/etc/cron.d/metrics").as_deref(),
            Some(
                "# managed by puppet\n17 *\t* * *\troot\tcd / && tidy\n\n\
                 #shuvjobs-disabled# */5 * * * * nobody /usr/local/bin/metrics --batch\n"
            )
        );
        writer(&host)
            .set_enabled("/etc/cron.d/metrics:4", true, ApplyMode::Apply)
            .unwrap();
        assert_eq!(
            host.file_contents("/etc/cron.d/metrics").as_deref(),
            Some(CRON_D)
        );
    }

    #[test]
    fn toggling_a_line_that_is_already_in_that_state_does_nothing() {
        let host = Arc::new(
            FakeHost::new()
                .with_policy(sudoer())
                .root_only("/etc/")
                .file("/etc/cron.d/metrics", CRON_D),
        );
        let outcome = writer(&host)
            .set_enabled("/etc/cron.d/metrics:4", true, ApplyMode::Apply)
            .unwrap();
        assert!(outcome.changes.is_empty());
        assert!(
            outcome
                .notes
                .iter()
                .any(|note| note.contains("already enabled")),
            "{:?}",
            outcome.notes
        );
        assert_eq!(
            host.file_contents("/etc/cron.d/metrics").as_deref(),
            Some(CRON_D)
        );
    }

    #[test]
    fn disabling_a_per_user_job_reinstalls_the_crontab_with_the_marker() {
        let before = format!("{BANNER}0 9 * * * /usr/local/bin/report\n");
        let host = Arc::new(FakeHost::new().script("crontab -l", 0, &before, "").script(
            "crontab -",
            0,
            "",
            "",
        ));
        writer(&host)
            .set_enabled("user:tester:4", false, ApplyMode::Apply)
            .unwrap();
        assert_eq!(
            stdin_of(&host, "crontab -"),
            "#shuvjobs-disabled# 0 9 * * * /usr/local/bin/report\n"
        );
    }

    #[test]
    fn a_run_parts_script_is_toggled_with_its_executable_bit() {
        let host = Arc::new(
            FakeHost::new()
                .with_policy(sudoer())
                .script("chmod a-x '/etc/cron.daily/backup'", 0, "", "")
                .script("chmod a+x '/etc/cron.daily/backup'", 0, "", ""),
        );
        for enabled in [false, true] {
            let outcome = writer(&host)
                .set_enabled("/etc/cron.daily/backup", enabled, ApplyMode::Apply)
                .unwrap();
            assert_eq!(outcome.id.as_deref(), Some("/etc/cron.daily/backup"));
        }
        assert_eq!(
            host.calls(),
            vec![
                call("chmod a-x '/etc/cron.daily/backup'", None, Privilege::Root),
                call("chmod a+x '/etc/cron.daily/backup'", None, Privilege::Root),
            ]
        );
    }

    #[test]
    fn the_writer_answers_for_cron() {
        let host = Arc::new(FakeHost::new());
        assert_eq!(writer(&host).kind(), TaskSourceKind::Cron);
    }
}
