[package]
name = "shuvjobs-core"
version.workspace = true
edition.workspace = true
license-file = "../../LICENSE"
repository.workspace = true
rust-version.workspace = true
description = "Domain model and query operations for ShuvJobs"

[dependencies]
chrono = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
